// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CraneFileManager.Domain.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CraneFileManager.Domain.EntityFrameworkConfigurations
{
    public partial class FileConfiguration : IEntityTypeConfiguration<CraneFileManager.Domain.Entities.Models.File>
    {
        public void Configure(EntityTypeBuilder<CraneFileManager.Domain.Entities.Models.File> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__File__3214EC074F07067A");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Description).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.IsRemove).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.OrginalName).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.DisplayName).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Path).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Size).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.FileType).WithMany(p => p.Files).HasConstraintName("FK_FileTypeId_forFile");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CraneFileManager.Domain.Entities.Models.File> entity);
    }
}
