// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CraneFileManager.Domain.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CraneFileManager.Domain.EntityFrameworkConfigurations
{
    public partial class FileTrashCanConfiguration : IEntityTypeConfiguration<FileTrashCan>
    {
        public void Configure(EntityTypeBuilder<FileTrashCan> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__FileTras__3214EC07D403E5D7");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.TakeofTrashDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.ThrowTrashDate).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.File).WithMany(p => p.FileTrashCans).HasConstraintName("FK_FileId_forFileTrashCan");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FileTrashCan> entity);
    }
}
