// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CraneFileManager.Domain.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CraneFileManager.Domain.EntityFrameworkConfigurations
{
    public partial class FileShareConfiguration : IEntityTypeConfiguration<CraneFileManager.Domain.Entities.Models.FileShare>
    {
        public void Configure(EntityTypeBuilder<CraneFileManager.Domain.Entities.Models.FileShare> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__FileShar__3214EC075BDEB216");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.File).WithMany(p => p.FileShares).HasConstraintName("FK_FileId_forFileShare");

            entity.HasOne(d => d.User).WithMany(p => p.FileShares).HasConstraintName("FK_UserId_forFileShare");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CraneFileManager.Domain.Entities.Models.FileShare> entity);
    }
}
