// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CraneFileManager.Domain.Entities.IdentityAuth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CraneFileManager.Domain.EntityFrameworkConfigurations
{
    public partial class RoleClaimConfiguration : IEntityTypeConfiguration<RoleClaim>
    {
        public void Configure(EntityTypeBuilder<RoleClaim> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__RoleClai__3214EC0728C9B922");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleClaims).HasConstraintName("FK_RoleId_forRoleClaim");

            entity.HasOne(d => d.RolePermission).WithMany(p => p.RoleClaims).HasConstraintName("FK_RolePermissionId_forRoleClaim");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoleClaim> entity);
    }
}
