// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CraneFileManager.Domain.Entities.IdentityAuth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CraneFileManager.Domain.EntityFrameworkConfigurations
{
    public partial class RolePermissionConfiguration : IEntityTypeConfiguration<RolePermission>
    {
        public void Configure(EntityTypeBuilder<RolePermission> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__RolePerm__3214EC07CC5B73BC");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Method).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.MethodDescription).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(NULL)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RolePermission> entity);
    }
}
