// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CraneFileManager.Domain.Entities.IdentityAuth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CraneFileManager.Domain.EntityFrameworkConfigurations
{
    public partial class UserClaimConfiguration : IEntityTypeConfiguration<UserClaim>
    {
        public void Configure(EntityTypeBuilder<UserClaim> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__UserClai__3214EC07A38C720D");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.User).WithMany(p => p.UserClaims).HasConstraintName("FK_UserId_forUserClaim");

            entity.HasOne(d => d.UserPermition).WithMany(p => p.UserClaims).HasConstraintName("FK_UserPermitionId_forUserClaim");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserClaim> entity);
    }
}
