// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CraneFileManager.Domain.Entities.IdentityAuth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CraneFileManager.Domain.EntityFrameworkConfigurations
{
    public partial class UserPermissionConfiguration : IEntityTypeConfiguration<UserPermission>
    {
        public void Configure(EntityTypeBuilder<UserPermission> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__UserPerm__3214EC070D532386");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UserAccess).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.UserAccessDescription).HasDefaultValueSql("(NULL)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserPermission> entity);
    }
}
