// <auto-generated />
using System;
using CraneFileManager.Persistence.Contexts.CraneFileManagerDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraneFileManager.Persistence.Migrations
{
    [DbContext(typeof(CraneFileManagerContext))]
    [Migration("20260523125012_CraneFileManagerContextMigration")]
    partial class CraneFileManagerContextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC078D6B7E10");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RolePermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__RoleClai__3214EC0728C9B922");

                    b.HasIndex("RoleId");

                    b.HasIndex("RolePermissionId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("MethodDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__RolePerm__3214EC07CC5B73BC");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("Birthday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool?>("IsBlcok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("SecretKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC07150C006D");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserPermitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__UserClai__3214EC07A38C720D");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPermitionId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__UserNoti__3214EC070206A0D0");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotification");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("UserAccess")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("UserAccessDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__UserPerm__3214EC070D532386");

                    b.ToTable("UserPermission");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__UserRole__3214EC079612DB4B");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("FileTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsRemove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isRemove")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("OrginalName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__File__3214EC074F07067A");

                    b.HasIndex("FileTypeId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.FileShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__FileShar__3214EC075BDEB216");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("FileShare");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.FileTrashCan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TakeofTrashDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("ThrowTrashDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__FileTras__3214EC07D403E5D7");

                    b.HasIndex("FileId");

                    b.ToTable("FileTrashCan");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.FileType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__FileType__3214EC07F9EC5D14");

                    b.ToTable("FileType");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("NotificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07600A5E25");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.UserFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__UserFile__3214EC076B9AF94C");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFile");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.RoleClaim", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RoleId_forRoleClaim");

                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.RolePermission", "RolePermission")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RolePermissionId")
                        .HasConstraintName("FK_RolePermissionId_forRoleClaim");

                    b.Navigation("Role");

                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserClaim", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserId_forUserClaim");

                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.UserPermission", "UserPermition")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserPermitionId")
                        .HasConstraintName("FK_UserPermitionId_forUserClaim");

                    b.Navigation("User");

                    b.Navigation("UserPermition");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserNotification", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .HasConstraintName("FK_NotificationId_forUserNotification");

                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserId_forUserNotification");

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserRole", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RoleId_forUserRole");

                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserId_forUserRole");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.File", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.Models.FileType", "FileType")
                        .WithMany("Files")
                        .HasForeignKey("FileTypeId")
                        .HasConstraintName("FK_FileTypeId_forFile");

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.FileShare", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.Models.File", "File")
                        .WithMany("FileShares")
                        .HasForeignKey("FileId")
                        .HasConstraintName("FK_FileId_forFileShare");

                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.User", "User")
                        .WithMany("FileShares")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserId_forFileShare");

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.FileTrashCan", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.Models.File", "File")
                        .WithMany("FileTrashCans")
                        .HasForeignKey("FileId")
                        .HasConstraintName("FK_FileId_forFileTrashCan");

                    b.Navigation("File");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.UserFile", b =>
                {
                    b.HasOne("CraneFileManager.Domain.Entities.Models.File", "File")
                        .WithMany("UserFiles")
                        .HasForeignKey("FileId")
                        .HasConstraintName("FK_FileId_forUseFile");

                    b.HasOne("CraneFileManager.Domain.Entities.IdentityAuth.User", "User")
                        .WithMany("UserFiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserId_forUseFile");

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.RolePermission", b =>
                {
                    b.Navigation("RoleClaims");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.User", b =>
                {
                    b.Navigation("FileShares");

                    b.Navigation("UserClaims");

                    b.Navigation("UserFiles");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.IdentityAuth.UserPermission", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.File", b =>
                {
                    b.Navigation("FileShares");

                    b.Navigation("FileTrashCans");

                    b.Navigation("UserFiles");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.FileType", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("CraneFileManager.Domain.Entities.Models.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
